In [ ]:
!pip install -U liblinear-official

Requirement already satisfied: liblinear-official in /usr/local/lib/python3.7/dist-packages (2.43.0)
Requirement already satisfied: scipy in /usr/local/lib/python3.7/dist-packages (from liblinear-official) (1.4.1)
Requirement already satisfied: numpy>=1.13.3 in /usr/local/lib/python3.7/dist-packages (from scipy->liblinear-official) (1.19.5)

In [ ]:
from liblinear.liblinearutil import *
import pandas as pd
import numpy as np
from sklearn.preprocessing import PolynomialFeatures

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
train_data = pd.read_excel('/content/drive/MyDrive/Colab Notebooks/hw4_train.xlsx', header=0)
train_X = train_data.drop('y', axis=1)
train_y = train_data['y']
display(train_data.head(3))
# 3rd order transformation
train_X = np.asarray(train_X)
poly = PolynomialFeatures(3)
train_X = poly.fit_transform(train_X)
train_X = pd.DataFrame(train_X)
print(train_X.shape)
train_X.head(3)

       x1      x2      x3      x4      x5      x6  y
0 -2.1539 -0.2103  1.6674  0.4690  0.9755 -2.9343  1
1 -1.8905  1.0685 -1.9168  0.9010 -2.2820  2.7919 -1
2 -1.3220  1.7971  0.5596  2.7259  1.7738  0.9715 -1

(200, 84)

/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:590: FutureWarning: np.matrix usage is deprecated in 1.0 and will raise a TypeError in 1.2. Please convert to a numpy array with np.asarray. For more information see: https://numpy.org/doc/stable/reference/generated/numpy.matrix.html
  FutureWarning,
/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:590: FutureWarning: np.matrix usage is deprecated in 1.0 and will raise a TypeError in 1.2. Please convert to a numpy array with np.asarray. For more information see: https://numpy.org/doc/stable/reference/generated/numpy.matrix.html
  FutureWarning,

    0       1       2       3   ...         80         81         82         83
0  1.0 -2.1539 -0.2103  1.6674  ...   0.928286  -2.792281   8.399169 -25.264665
1  1.0 -1.8905  1.0685 -1.9168  ... -11.883570  14.538886 -17.787518  21.762039
2  1.0 -1.3220  1.7971  0.5596  ...   5.581025   3.056695   1.674134   0.916914

[3 rows x 84 columns]

In [ ]:
test_data = pd.read_excel('/content/drive/MyDrive/Colab Notebooks/hw4_test.xlsx', header=0)
test_X = test_data.drop('y', axis=1)
test_y = test_data['y']
display(test_data.head(3))
# 3rd order transformation
test_X = np.asarray(test_X)
poly = PolynomialFeatures(3)
test_X = poly.fit_transform(test_X)
test_X = pd.DataFrame(test_X)
print(test_X.shape)
test_X.head(3)

       x1      x2      x3      x4      x5      x6  y
0 -1.7855 -0.3218 -1.0800  1.4493 -0.3805  1.2058 -1
1  0.2638  0.9553  1.5076  0.4492  1.8627 -1.2817 -1
2  0.9679 -2.2672 -0.0140  2.1881  0.3232  1.5857  1

(800, 84)

/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:590: FutureWarning: np.matrix usage is deprecated in 1.0 and will raise a TypeError in 1.2. Please convert to a numpy array with np.asarray. For more information see: https://numpy.org/doc/stable/reference/generated/numpy.matrix.html
  FutureWarning,
/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:590: FutureWarning: np.matrix usage is deprecated in 1.0 and will raise a TypeError in 1.2. Please convert to a numpy array with np.asarray. For more information see: https://numpy.org/doc/stable/reference/generated/numpy.matrix.html
  FutureWarning,

    0       1       2       3   ...        80        81        82        83
0  1.0 -1.7855 -0.3218 -1.0800  ... -0.055089  0.174576 -0.553229  1.753177
1  1.0  0.2638  0.9553  1.5076  ...  6.462919 -4.447052  3.059960 -2.105519
2  1.0  0.9679 -2.2672 -0.0140  ...  0.033761  0.165639  0.812668  3.987155

[3 rows x 84 columns]

In [ ]:
# 12
train_y = np.array(train_y)
train_X = np.asarray(train_X)
test_y = np.array(test_y)
test_X = np.asarray(test_X)
prob  = problem(train_y, train_X)
param = parameter('-s 0 -e 0.000001 -c 5000')
model = train(prob, param)
p_labs, p_acc, p_vals = predict(test_y, test_X, model)
print(p_acc)

Accuracy = 87.625% (701/800) (classification)
(87.625, 0.495, 0.5663878365260584)

In [ ]:
# 13
train_y = np.array(train_y)
train_X = np.asarray(train_X)
test_y = np.array(test_y)
test_X = np.asarray(test_X)
prob  = problem(train_y, train_X)
param = parameter('-s 0 -e 0.000001 -c 0.00005')
model = train(prob, param)
p_labs, p_acc, p_vals = predict(train_y, train_X, model)
print(p_acc)

Accuracy = 82% (164/200) (classification)
(82.0, 0.72, 0.4095539166877984)

In [ ]:
# 14
# preparing train
train_data = pd.read_excel('/content/drive/MyDrive/Colab Notebooks/hw4_train.xlsx', header=0)
train_X = train_data.drop('y', axis=1)
train_y = train_data['y']
display(train_data.head(3))
# 3rd order transformation
train_X = np.asarray(train_X)
poly = PolynomialFeatures(3)
train_X = poly.fit_transform(train_X)
train_X = pd.DataFrame(train_X)
print(train_X.shape)
train_X.head(3)

# preparing test
test_data = pd.read_excel('/content/drive/MyDrive/Colab Notebooks/hw4_test.xlsx', header=0)
test_X = test_data.drop('y', axis=1)
test_y = test_data['y']
display(test_data.head(3))
# 3rd order transformation
test_X = np.asarray(test_X)
poly = PolynomialFeatures(3)
test_X = poly.fit_transform(test_X)
test_X = pd.DataFrame(test_X)
print(test_X.shape)
test_X.head(3)

# train, select, and predict
val_y = np.array(train_y[120:])
val_X = np.array(train_X.iloc[120:, :])
train_y = np.array(train_y[:120])
train_X = np.asarray(train_X.iloc[:120, :])

print('validation size:', len(val_y), len(val_X))
print('train size:', len(train_y), len(train_X))

test_y = np.array(test_y)
test_X = np.asarray(test_X)
prob  = problem(train_y, train_X)
param = parameter('-s 0 -e 0.000001 -c 0.005')
model = train(prob, param)
p_labs, p_acc, p_vals = predict(val_y, val_X, model)
print('Eval:', p_acc)
p_labs, p_acc, p_vals = predict(test_y, test_X, model)
print('Eout(w*):', p_acc)

       x1      x2      x3      x4      x5      x6  y
0 -2.1539 -0.2103  1.6674  0.4690  0.9755 -2.9343  1
1 -1.8905  1.0685 -1.9168  0.9010 -2.2820  2.7919 -1
2 -1.3220  1.7971  0.5596  2.7259  1.7738  0.9715 -1

(200, 84)

       x1      x2      x3      x4      x5      x6  y
0 -1.7855 -0.3218 -1.0800  1.4493 -0.3805  1.2058 -1
1  0.2638  0.9553  1.5076  0.4492  1.8627 -1.2817 -1
2  0.9679 -2.2672 -0.0140  2.1881  0.3232  1.5857  1

(800, 84)
validation size: 80 80
train size: 120 120
Accuracy = 93.75% (75/80) (classification)
Eval: (93.75, 0.25, 0.7770345596432553)
Accuracy = 92.5% (740/800) (classification)
Eout(w*): (92.5, 0.3, 0.722637123551138)

In [ ]:
# 15
# preparing train
train_data = pd.read_excel('/content/drive/MyDrive/Colab Notebooks/hw4_train.xlsx', header=0)
train_X = train_data.drop('y', axis=1)
train_y = train_data['y']
display(train_data.head(3))
# 3rd order transformation
train_X = np.asarray(train_X)
poly = PolynomialFeatures(3)
train_X = poly.fit_transform(train_X)
train_X = pd.DataFrame(train_X)
print(train_X.shape)
train_X.head(3)

# preparing test
test_data = pd.read_excel('/content/drive/MyDrive/Colab Notebooks/hw4_test.xlsx', header=0)
test_X = test_data.drop('y', axis=1)
test_y = test_data['y']
display(test_data.head(3))
# 3rd order transformation
test_X = np.asarray(test_X)
poly = PolynomialFeatures(3)
test_X = poly.fit_transform(test_X)
test_X = pd.DataFrame(test_X)
print(test_X.shape)
test_X.head(3)

# train, select, and predict
train_y = np.array(train_y)
train_X = np.asarray(train_X)
print('train size:', len(train_y), len(train_X))

test_y = np.array(test_y)
test_X = np.asarray(test_X)
prob  = problem(train_y, train_X)
param = parameter('-s 0 -e 0.000001 -c 0.005')
model = train(prob, param)
p_labs, p_acc, p_vals = predict(test_y, test_X, model)
print('Eout(w*):', p_acc)

       x1      x2      x3      x4      x5      x6  y
0 -2.1539 -0.2103  1.6674  0.4690  0.9755 -2.9343  1
1 -1.8905  1.0685 -1.9168  0.9010 -2.2820  2.7919 -1
2 -1.3220  1.7971  0.5596  2.7259  1.7738  0.9715 -1

(200, 84)

       x1      x2      x3      x4      x5      x6  y
0 -1.7855 -0.3218 -1.0800  1.4493 -0.3805  1.2058 -1
1  0.2638  0.9553  1.5076  0.4492  1.8627 -1.2817 -1
2  0.9679 -2.2672 -0.0140  2.1881  0.3232  1.5857  1

(800, 84)
train size: 200 200
Accuracy = 92.75% (742/800) (classification)
Eout(w*): (92.75, 0.29, 0.7311043053833289)

In [ ]:
# 16
# preparing train
train_data = pd.read_excel('/content/drive/MyDrive/Colab Notebooks/hw4_train.xlsx', header=0)
train_X = train_data.drop('y', axis=1)
train_y = train_data['y']
display(train_data.head(3))
# 3rd order transformation
train_X = np.asarray(train_X)
poly = PolynomialFeatures(3)
train_X = poly.fit_transform(train_X)
train_X = pd.DataFrame(train_X)
print(train_X.shape)
train_X.head(3)

# preparing test
test_data = pd.read_excel('/content/drive/MyDrive/Colab Notebooks/hw4_test.xlsx', header=0)
test_X = test_data.drop('y', axis=1)
test_y = test_data['y']
display(test_data.head(3))
# 3rd order transformation
test_X = np.asarray(test_X)
poly = PolynomialFeatures(3)
test_X = poly.fit_transform(test_X)
test_X = pd.DataFrame(test_X)
print(test_X.shape)
test_X.head(3)

avg_acc = 0
for i in range(5):
  # train, select, and predict
  val_y = train_y[40 * i: 40 * (i + 1)]
  val_X = train_X.iloc[40 * i: 40 * (i + 1), :]
  training_y = np.array(train_y.drop(val_y.index, axis=0))
  training_X = np.asarray(train_X.drop(val_X.index, axis=0))
  val_y = np.array(val_y)
  val_X = np.array(val_X)

  print('validating: {}~{}'.format(40 * i, 40 * (i + 1)))
  print('validation size:', len(val_y), len(val_X))
  print('train size:', len(training_y), len(training_X))

  testing_y = np.array(test_y)
  testing_X = np.asarray(test_X)
  prob  = problem(training_y, training_X)
  param = parameter('-s 0 -e 0.000001 -c 5000')
  model = train(prob, param)
  p_labs, p_acc, p_vals = predict(val_y, val_X, model)
  print('Eval:', p_acc)
  print()
  avg_acc += p_acc[0]
avg_acc /= 5
print('Ecv:', avg_acc)

       x1      x2      x3      x4      x5      x6  y
0 -2.1539 -0.2103  1.6674  0.4690  0.9755 -2.9343  1
1 -1.8905  1.0685 -1.9168  0.9010 -2.2820  2.7919 -1
2 -1.3220  1.7971  0.5596  2.7259  1.7738  0.9715 -1

(200, 84)

       x1      x2      x3      x4      x5      x6  y
0 -1.7855 -0.3218 -1.0800  1.4493 -0.3805  1.2058 -1
1  0.2638  0.9553  1.5076  0.4492  1.8627 -1.2817 -1
2  0.9679 -2.2672 -0.0140  2.1881  0.3232  1.5857  1

(800, 84)
validating: 0~40
validation size: 40 40
train size: 160 160
Accuracy = 82.5% (33/40) (classification)
Eval: (82.5, 0.7, 0.4208754208754209)

validating: 40~80
validation size: 40 40
train size: 160 160
Accuracy = 82.5% (33/40) (classification)
Eval: (82.5, 0.7, 0.4208754208754209)

validating: 80~120
validation size: 40 40
train size: 160 160
Accuracy = 70% (28/40) (classification)
Eval: (70.0, 1.2, 0.16161616161616163)

validating: 120~160
validation size: 40 40
train size: 160 160
Accuracy = 82.5% (33/40) (classification)
Eval: (82.5, 0.7, 0.42355889724310775)

validating: 160~200
validation size: 40 40
train size: 160 160
Accuracy = 87.5% (35/40) (classification)
Eval: (87.5, 0.5, 0.6)

Ecv: 81.0

In [ ]:
help(train)

Help on function train in module liblinear.liblinearutil:

train(arg1, arg2=None, arg3=None)
    train(y, x [, options]) -> model | ACC

    y: a list/tuple/ndarray of l true labels (type must be int/double).

    x: 1. a list/tuple of l training instances. Feature vector of
          each training instance is a list/tuple or dictionary.

       2. an l * n numpy ndarray or scipy spmatrix (n: number of features).

    train(prob [, options]) -> model | ACC
    train(prob, param) -> model | ACC

    Train a model from data (y, x) or a problem prob using
    'options' or a parameter param.

    If '-v' is specified in 'options' (i.e., cross validation)
    either accuracy (ACC) or mean-squared error (MSE) is returned.

    options:
        -s type : set type of solver (default 1)
          for multi-class classification
             0 -- L2-regularized logistic regression (primal)
             1 -- L2-regularized L2-loss support vector classification (dual)
             2 -- L2-regularized L2-loss support vector classification (primal)
             3 -- L2-regularized L1-loss support vector classification (dual)
             4 -- support vector classification by Crammer and Singer
             5 -- L1-regularized L2-loss support vector classification
             6 -- L1-regularized logistic regression
             7 -- L2-regularized logistic regression (dual)
          for regression
            11 -- L2-regularized L2-loss support vector regression (primal)
            12 -- L2-regularized L2-loss support vector regression (dual)
            13 -- L2-regularized L1-loss support vector regression (dual)
          for outlier detection
            21 -- one-class support vector machine (dual)
        -c cost : set the parameter C (default 1)
        -p epsilon : set the epsilon in loss function of SVR (default 0.1)
        -e epsilon : set tolerance of termination criterion
            -s 0 and 2
                |f'(w)|_2 <= eps*min(pos,neg)/l*|f'(w0)|_2,
                where f is the primal function, (default 0.01)
            -s 11
                |f'(w)|_2 <= eps*|f'(w0)|_2 (default 0.0001)
            -s 1, 3, 4, 7, and 21
                Dual maximal violation <= eps; similar to libsvm (default 0.1 except 0.01 for -s 21)
            -s 5 and 6
                |f'(w)|_inf <= eps*min(pos,neg)/l*|f'(w0)|_inf,
                where f is the primal function (default 0.01)
            -s 12 and 13
                |f'(alpha)|_1 <= eps |f'(alpha0)|,
                where f is the dual function (default 0.1)
        -B bias : if bias >= 0, instance x becomes [x; bias]; if < 0, no bias term added (default -1)
        -R : not regularize the bias; must with -B 1 to have the bias; DON'T use this unless you know what it is
            (for -s 0, 2, 5, 6, 11)"
        -wi weight: weights adjust the parameter C of different classes (see README for details)
        -v n: n-fold cross validation mode
        -C : find parameters (C for -s 0, 2 and C, p for -s 11)
        -q : quiet mode (no outputs)